### ISSUE TITLE
CSRF Error on fresh instance

### ISSUE THREAD

**Issue by theodotdot** [app-generator/flask-dashboard-volt#1]
Hi,

I am trying to run the app locally and haven't been able to push past this error:

> RuntimeError: A secret key is required to use CSRF.

I tried setting the secret key manually in run.py with `app.config["SECRET_KEY"] = "test"` and trying to change the value in the .env file but nothing seems to change or work. 

At this point I'm still new to Flask and web development in general so forgive me if the problem is trivial.

Thanks

**Comment by app-generator** [comment]
Hello, 

Please export the FLASK_APP variable before executing `flask run`:

```bash
$ # Set the FLASK_APP environment variable
$ (Unix/Mac) export FLASK_APP=run.py
$ (Windows) set FLASK_APP=run.py
$ (Powershell) $env:FLASK_APP = ".\run.py"
```

**Comment by theodotdot** [comment]
Hi, 

Thanks for you answer!

Here is what I did after extracting the folder (I'm on windows):


```
 virtualenv env
.\env\Scripts\activate

pip3 install -r requirements.txt

set FLASK_APP=run.py

flask run --host=0.0.0.0 --port=5000
```

I tried doing it again but with no success.

**Comment by app-generator** [comment]
try to set the FLASK_APP using the command: 

```
$env:FLASK_APP = ".\run.py"
```

**Comment by theodotdot** [comment]
I tried that command both in the VSCode terminal and in a separate powershell window and in both cases it gives me the error:

> env:FLASK_APP : The term 'env:FLASK_APP' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by app-generator** [comment]
We cannot reproduce this issue on our testbeds. 
Cross testes we executed on the following environments:
- Python3
- Linux (RHEL & Debian): CentOS 7 and Ubuntu 18.04 LTS
- Windows 10 32/64b

The issues will be closed.
