### ISSUE TITLE
Navigation for medium size screens devices not showing menu elements

### ISSUE THREAD

**Issue by andresmascl** [app-generator/flask-dashboard-volt#2]
Hello,

When transitioning from top nav menu to hamburger menu on the theme's main page, the menu items are displayed with white font color on medium size screens, thus not causing contrast with the white background.

To replicate shrink the browser window to when the navigation menu changes to hamburger icon.

**Comment by app-generator** [comment]
Hello @andresmascl,

Please upload an image or specify the steps to reproduce the issue.

Thank you!

**Comment by andresmascl** [comment]
![flask-volt-github](https://user-images.githubusercontent.com/26497935/109439499-4e321280-7a0d-11eb-90d9-de4d3d204f4c.png)
Please find the screenshot attached

**Comment by app-generator** [comment]
Hello @andresmascl, 

Please re-test this issue using the latest [release](https://github.com/app-generator/flask-dashboard-volt/releases) **https://github.com/app-generator/flask-dashboard-volt/releases**

**Comment by DenisShaikin** [comment]
Hello, I've just loaded the last version of project, and I confirm the probleme on index.html with the last volt.css.  If I change  the volt.css for the demo version of this file, menu is visible.
![image](https://user-images.githubusercontent.com/35135287/200166545-99a8c07a-811a-4a95-b604-ff1a5648e858.png)

**Comment by DenisShaikin** [comment]
The same file index.html with volt.css downloaded from Volt Dashboard Demo. 
![image](https://user-images.githubusercontent.com/35135287/200166669-46469e7b-4427-44f5-ae7a-7fd294291b7d.png)
