### ISSUE TITLE
ImportError: cannot import name 'Binary' from 'sqlalchemy'

### ISSUE THREAD

**Issue by carenaudo** [app-generator/flask-dashboard-volt#4]
Binary should be changed to LargeBinary in the file models.py to work on newer versions of sqlalchemy

``volt-master\app\base\models.py", line 7, in <module>
    from sqlalchemy import Binary, Column, Integer, String
ImportError: cannot import name 'Binary' from 'sqlalchemy' ``

**Comment by app-generator** [comment]
Hello @carenaudo, 

Thank you for using our products. 
This evolution will be included in the next iteration of the product. 

Let us know if you have other suggestions. 
We have an active reward plan to cover such efforts. 

This issue will remain open.

**Comment by app-generator** [comment]
Fixed in **v1.0.5**.
